### ISSUE TITLE
Our cruncher instance does not produce highways tiles

### ISSUE THREAD

**Issue by nerik** [GFDRR/osm-analytics-cruncher#12]
https://osm-analytics.vizzuality.com/highways/5/17/15.pbf

Maybe related to https://github.com/hotosm/osm-analytics/issues/63 ?

**Comment by tiagojsag** [comment]
https://github.com/GFDRR/osm-analytics-cruncher/commit/31a572214a029e7d7f499f8392aa3e96390ba417
